### PR TITLE
Add ability to populate tree from dictionary

### PR DESCRIPTION
**Pull request by dterg**
After creating the tree object, calling import_tree_dict and passing a hierarchical dictionary will populate the tree with the nodes.

```
tree = Tree()
jsonData = {'id': 'root', 'name': 'root', 'children': [{'id': 'child1', 'name':'child1', 'children':[]},{'id': 'child2','name':'child2', 'children':[]}]}
tree.import_tree_dict(jsonData)
tree.show()

```

### CODE REVIEW

**Comment by ocervell** [comment]
What's preventing this from being merged ?

**Comment by ocervell** [comment]
@caesar0301 Could you please look at this and merge it ? A few people are waiting for this feature to be merged.

**Comment by caesar0301** [comment]
@ocervell Yes, I am designing a unified interface to manipulate different formats. See #85. Thanks @dterg ahead. Your code will be merged, maybe, in a different way.

**Comment by jiwidi** [comment]
Why isn't this merged? #85 has been open since dec 2017 and the feature is not yet implemented. We have a working solution here, why not merging if you can't continue with #85?

**Pull request closed without merging**
