### PR TITLE
Nodes tree-wise  bpointer/fpointers

### PR DESCRIPTION
**Pull request by leonardbinet**
I encountered the following conditions:
- having to deal with lots (potentially hundreds of thousands) of nodes containing data
- having generate multiple subtrees without impacting initial tree

The only solution I had was to create for each subtree a deepcopy, but it was very greedy and expensive in terms of memory.

This pull-request implements the ability to generate shallow copies of trees (no deep-copy of nodes), and mutate multiple shallow copies of the same tree without impacting other trees hierarchies.

I do so by assigning `Nodes` not a single `_bpointer` `_fpointer`, but one per shallow copy of tree.

### CODE REVIEW

**Comment by leonardbinet** [comment]
removed no-longer supported versions on python
Capture d’écran 2019-10-13 à 00 58 32

**Comment by caesar0301** [comment]
Hi @leonardbinet ,
It is really a nice idea to` get shallow copy of subtree`. I was excited with your proposal in email before dealing with this pull request. However this implementation requires more consideration as it will break the compatibility I have been keeping for a long time. Dependencies from some existing projects invoking API `bpointer` and `fpointer` will be broken unexpectedly.
Let's find out a more compatible version for this feature?
Xiaming

**Comment by alk-lbinet** [comment]
@caesar0301 indeed I'll think about that

**Comment by alk-lbinet** [comment]
@caesar0301 I've updated PR to avoid any breaking change, + minor correction on `__contains__` method ([must return boolean](https://docs.python.org/3/reference/datamodel.html#object.__contains__))

**Comment by alk-lbinet** [comment]
hi @caesar0301, have you had time to have a look? thx in advance!

**Comment by caesar0301** [comment]
@alk-lbinet Sorry for delayed response. Busy with some work. Could you give a merge into branch `feature/tree-wise-node-pointer`? I have some idea to try a tider and more unified API based on your improvement. Thanks!

**Comment by leonardbinet** [comment]
@caesar0301 I've created a PR on the `feature/tree-wise-node-pointer` branch, but having no access on your repo I cannot merge though 🙂 ,  looking forward to seeing the unified API!

**Comment by caesar0301** [comment]
@leonardbinet Thank you. Close this issue for now. Let working on the new branch (#126 ).

**Pull request closed without merging**
