### PR TITLE
Added all_nodes_iter and filter_nodes methods to Tree class

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**
This is a small pull request that includes test cases.

Added the method all_nodes_iter to make it more in line with python switching over to iterators instead of putting everything in lists. It's compatible with python 2.

Added a filter_nodes to allow filtering of the nodes based on their properties.

### CODE REVIEW

**Comment by BebeSparkelSparkel** [comment]
I'm also willing to update the docs if you want me too.

**Comment by caesar0301** [comment]
Thanks! :+1:

**Comment by BebeSparkelSparkel** [comment]
No problem. Do you need any other help with this project?

**Comment by caesar0301** [comment]
Yes. ur question in #65 is a great feature. I think many applications would need that. Lets talk under that thread.

**Pull request merged**
