### PR TITLE
Add from dict

### PR DESCRIPTION
**Pull request by gaoyukid**
In work, i usually need to deal with raw data in child:parent as a dict format - i need to rewrite from_dict function a lot to form a tree so i thought it could be a plugin

### CODE REVIEW

**Comment by gaoyukid** [comment]
Ready for review

**Comment by caesar0301** [comment]
> Ready for review

The plugin extension is deprecated and will be removed in near future. We recommend to enrich `to_xxx` and from `from_xxx` routines. In this case, a static method of `from_dict` would be appropriate.

**Comment by gaoyukid** [comment]
> > Ready for review
> 
> The plugin extension is deprecated and will be removed in near future. We recommend to enrich `to_xxx` and from `from_xxx` routines. In this case, a static method of `from_dict` would be appropriate.

done - however, i'd like to point out that the from_dict schema is different than the to_dict schema, which can cause confusion

**Comment by caesar0301** [comment]
@gaoyukid Please help us to fix the flake8 linting.

**Comment by caesar0301** [comment]
Merged manually

**Pull request closed without merging**
